//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegDiff.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegDiff.Test.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\AppEvents]
        ///
        ///[HKEY_CURRENT_USER\AppEvents\EventLabels]
        ///
        ///[HKEY_CURRENT_USER\AppEvents\EventLabels\.Default]
        ///@=&quot;Default Beep&quot;
        ///&quot;DispFileName&quot;=&quot;@mmres.dll,-5824&quot;
        ///
        ///[HKEY_CURRENT_USER\AppEvents\EventLabels\ActivatingDocument]
        ///@=&quot;Complete Navigation&quot;
        ///&quot;DispFileName&quot;=&quot;@ieframe.dll,-10321&quot;
        ///
        ///[HKEY_CURRENT_USER\AppEvents\EventLabels\AppGPFault]
        ///@=&quot;Program Error&quot;
        ///&quot;DispFileName&quot;=&quot;@mmres.dll,-5825&quot;
        ///
        ///[HKEY_CURRENT_USER\AppEvents\EventLabels\BlockedPo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegTestBaseFile {
            get {
                return ResourceManager.GetString("RegTestBaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\AppEvents]
        ///
        ///[HKEY_CURRENT_USER\AppEvents\EventLabels]
        ///
        ///[HKEY_CURRENT_USER\AppEvents\EventLabels\.Default]
        ///@=&quot;Default Beep2&quot;
        ///&quot;DispFileName&quot;=&quot;@mmres.dll,-5824&quot;
        ///
        ///[HKEY_CURRENT_USER\AppEvents\EventLabels\ActivatingDocument]
        ///@=&quot;Complete Navigation&quot;
        ///&quot;DispFileName&quot;=&quot;@ieframe.dll,-10321&quot;
        ///
        ///[HKEY_CURRENT_USER\AppEvents\EventLabels\AppGPFault]
        ///@=&quot;Program Error&quot;
        ///&quot;DispFileName&quot;=&quot;@mmres.dll,-5825&quot;
        ///
        ///[HKEY_CURRENT_USER\AppEvents\EventLabels\BlockedP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegTestChangesFile {
            get {
                return ResourceManager.GetString("RegTestChangesFile", resourceCulture);
            }
        }
    }
}
